name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version-file: .java-version
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package
